[[main]]
name = "tours"
url = "/tours"
weight = 1
[[main]]
name = "rental"
url = "/rental"
weight = 2
[[main]]
name = "training"
url = "/training"
weight = 3
[[main]]
name = "adventure"
url = "/adventure"
weight = 4
[[main]]
name = "testimonials"
url = "/testimonials"
weight = 5
[[main]]
name = "contact"
url = "contact"
weight = 6
#[[main]]
#name = "blog"
#url = "blog"
#weight = 6
#[[main]]
#name = "Pricing"
#url = "pricing"
#weight = 7


[[footer_left]]
name = "About Us"
url = "#"
[[footer_left]]
name = "Quick Start"
url = "#"
[[footer_left]]
name = "Pricing"
url = "pricing"

[[footer_middle]]
name = "Pricing"
url = "pricing"
[[footer_middle]]
name = "Platform"
url = "#"
[[footer_middle]]
name = "Features"
url = "#"

[[footer_right]]
name = "Rental Terms"
url = "/terms/rental-terms"
[[footer_right]]
name = "Tour Terms"
url = "/terms/tour-terms"
[[footer_right]]
name = "Insurance Details"
url = "/terms/insurance-details"
