author = "Martin Williamson"
blogCategoryType = "category"
contact_form_action = "#"
description = "This is meta description"
image = "images/logo.png"
logo = "images/motojoe.svg"
logo_width = "200px"
[cookies]
button = "I Accept"
content = "This site uses cookies. By continuing to use this website, you agree to their use."
enable = false
expire_days = 2
[navigation_button]
enable = true
label = "Get Started"
link = "contact"
[preloader]
enable = false
preloader = ""
[[social]]
icon = "fa fa-instagram"
link = "#motojoe.co.uk"
title = "instagram"
[[social]]
icon = "fab fa-facebook"
link = "#motojoe.co.uk"
title = "facebook"
[[social]]
icon = "fab fa-skype"
link = "#"
title = "skype"
[[social]]
icon = "fab fa-linkedin"
link = "#"
title = "linkedin"
