baseURL = "http://motojoes.netlify.com/"
disqusShortname = ""
googleAnalytics = ""
paginate = "3"
summaryLength = "15"
theme = "bigspring-light"
title = "MotoJoe"
[markup.goldmark.renderer]
unsafe = true
